### ISSUE TITLE
Direktlinks auf a.medonline

### ISSUE THREAD

**Issue by SimonAlm** [medizinmedien/cc-a-medonline-at#2]
Hallo @hostz-frank , @thob 
@sabne

Sabine braucht eventuell eine Direktlink Funktion von Whistle-Tabs für a. gleichlautend wie auf medonline. 
Ist dies ähnlich möglich oder auf a. nicht so einfach möglich: 
Beispiel, wo es gefragt wäre https://a.medonline.at/cyramza

**Comment by hostz-frank** [comment]
http://a.medonline.at/cyramza/#Informationen_f%C3%BCr_ApothekerInnen
Das habe ich jetzt für den aktuellen Style der o.g. Seite geändert (`style="meditabs-top-clean"`); die Nicht-Flat-Styles haben noch ältere Zozo-Bibliotheken eingebunden (die sind kleiner, unterstützen dafür aber das Deeplinking nicht, wie ich jetzt bemerke).

Kleine JS-Dateien haben auch etwas für sich - also bitte bescheidgeben, wenn **alle** Zozo-Styles das Deeplinking unterstützen sollen - dann hole ich das Update für die restlichen Zozo-Styles nach.

**Comment by SimonAlm** [comment]
danke frank!
