### ISSUE TITLE
Foto Gallery

### ISSUE THREAD

**Issue by SimonAlm** [medizinmedien/cc-a-medonline-at#3]
@hostz-frank 

Es gibt eine Anfrage/Wunsch mehr als 100 Bilder auf einer Seite anzuzeigen, das ist mit der Standardgallery nicht schön möglich.

Hast du eine Idee welches Plugin Gallery hier passend sein könnte?

ist eh nicht sicher ob wirs machen..

**Comment by hostz-frank** [comment]
Nein, keine spezielle Empfehlung - da bin ich leider nicht so auskunftskräftig.

**Comment by thob** [comment]
es geht eh welche speziell für Headway, sind auch installiert

**Comment by wozo** [comment]
kommt auf die anforderung an
aber das gallery plugin von headway haben wir (müssen wir nur aktivieren)
http://headwayrocket.com/blog/blocks/gallery/

auf welchen blog soll das?

**Comment by SimonAlm** [comment]
auf a.medonline bitte!

**Comment by wozo** [comment]
ok ist aktiviert

album kannst du hier zusammenstellen: https://a.medonline.at/wp-admin/edit.php?post_type=hwr_gallery
(testweise z.b. https://a.medonline.at/wp-admin/post.php?post=1849&action=edit&message=1)

hier wird das testalbum1 derzeit ausgegeben;
https://a.medonline.at/testseite2/
(pw: test1234)

**Comment by thob** [comment]
ich lösche den thread, oder @hostz-frank kann man den nach allgemein verschieben, weil dort gehört er hin?

**Comment by hostz-frank** [comment]
Ich habe keine Ahnung, ob sich der verschieben lässt.

**Comment by thob** [comment]
da gibt's was https://github-issue-mover.appspot.com/, will's aber nicht probieren.
@SimonAlm bitte den wichtigen Teil des Threads nach allgemein übernehmen, ich lösche dann diesen Thread hier, Danke
